language : node_js 
node_js :  
 - stable 
install:  
 - npm install 
 - node_modules/typescript/bin/tsc
script:  
 - npm run cover
# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"